name: textwrap
version: 2.0.0
description: Text wrapping and filling. It's a pure port of textwrap from Python.
repository: https://github.com/ykmnkmi/textwrap.dart
funding:
  - https://www.buymeacoffee.com/ykmnkmi

topics:
  - text

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
