name: textwrap
version: 1.2.0
description: Text wrapping and filling. It's a pure port of textwrap from Python.
repository: https://github.com/ykmnkmi/textwrap.dart
funding:
  - https://www.buymeacoffee.com/ykmnkmi

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
