name: textwrap
version: 2.1.0
description: Text wrapping and filling. It's a pure port of textwrap from Python.
repository: https://github.com/ykmnkmi/textwrap.dart

topics:
  - text

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  test_reflective_loader: ^0.4.0
