name: textwrap
description: Text wrapping and filling. It's a pure port of textwrap from Python.
version: 1.0.0
homepage: 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.2
