name: textwrap
version: 2.0.0-dev
description: Text wrapping and filling. It's a pure port of textwrap from Python.
repository: https://github.com/ykmnkmi/textwrap.dart
funding:
  - https://www.buymeacoffee.com/ykmnkmi

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
